{% set name = "dinglab-pollock" %}
{% set version = "0.0.13" %}

package:
##   name: "{{ name|lower }}"
  name: "pollock"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: b83b1f5fa53a83661f695b8e18ab02cc7f33a500a6d85573570bf4df3b365b8e

build:
  number: 0
  entry_points:
    - pollock=pollock.pollock:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - jupyter
    - pytest
    - matplotlib >=3.2.1
    - pandas >=1.0.0
    - pip
    - python
    - tar
    - scanpy >=1.4.4
    - scikit-learn ==0.23.1
    - scipy ==1.4.1
    - seaborn >=0.10.0
    - umap-learn >=0.3.10
    - shap
    - r-seurat >=3.0.2
    - r-devtools >=2.3.0

  run:
    - jupyter
    - pytest
    - matplotlib >=3.2.1
    - pandas >=1.0.0
    - python
    - pip
    - tar
    - scanpy >=1.4.4
    - scikit-learn ==0.23.1
    - scipy ==1.4.1
    - seaborn >=0.10.0
    - umap-learn >=0.3.10
    - shap
    - r-seurat >=3.0.2
    - r-devtools >=2.3.0
test:
  imports:
    - pollock
    - pollock.models
    - pollock.preprocessing
    - pollock.wrappers
    - pollock.wrappers.rwrappers
  commands:
    - pollock --help

about:
  home: "https://github.com/ding-lab/pollock"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "A tool for single cell classification and characterization."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - estorrs
